version: '3'
services:
  fanout-matches:
    stop_signal: SIGINT
    container_name: fanout-matches
    image: fanout-matches:latest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  fanout-players:
    stop_signal: SIGINT
    container_name: fanout-players
    image: fanout-players:latest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  filter-q1:
    stop_signal: SIGINT
    container_name: filter-q1
    image: filter-q1:latest
    entrypoint: python3 /main.py
    depends_on:
      - fanout-matches
    environment:
      - PYTHONUNBUFFERED=1
      # - MAX_CHUNKS_PER_BLOCK=21
    networks:
      - testing_net

  shard-exchanger-q2:
    stop_signal: SIGINT
    container_name: shard-exchanger-q2
    image: shard-exchanger-q2:latest
    entrypoint: python3 /main.py
    depends_on:
      - fanout-players
    environment:
      - PYTHONUNBUFFERED=1
      # - MAX_CHUNKS_PER_BLOCK=21
    networks:
      - testing_net

  group-by-nodes-q2:
    stop_signal: SIGINT
    container_name: group-by-nodes-q2
    image: group-by-nodes-q2:latest
    entrypoint: python3 /main.py
    depends_on:
      - shard-exchanger-q2
    environment:
      - PYTHONUNBUFFERED=1
      # - MAX_CHUNKS_PER_BLOCK=21
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24